sudo: required
services:
  - docker

before_install:
  - docker build -t elzilch0/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true elzilch0/react-test npm test

after_success:
  - docker build -t elzilch0/multi-client ./client
  - docker build -t elzilch0/multi-nginx ./nginx
  - docker build -t elzilch0/multi-server ./server
  - docker build -t elzilch0/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push elzilch0/multi-client
  - docker push elzilch0/multi-nginx
  - docker push elzilch0/multi-server
  - docker push elzilch0/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env-1
  bucket-name: elasticbeanstalk-us-east-1-661933406886
  bucket-path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
