sudo: required
services:
  - docker

before_install:
  - docker build -t elzhilch0/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true elzhilch0/react-test npm test

after_success:
  - docker build -t elzhilch0/multi-client ./client
  - docker build -t elzhilch0/multi-nginx ./nginx
  - docker build -t elzhilch0/multi-server ./server
  - docker build -t elzhilch0/multi-worker ./worker

  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD docker.io
  - docker push elzhilch0/multi-client
  - docker push elzhilch0/multi-nginx
  - docker push elzhilch0/multi-server
  - docker push elzhilch0/multi-worker
